language: java
addons:
  sonarcloud:
    organization: "$ORG_TOKEN"
    token:
      secure: frNEBOgRwOJppfsKpKozpyzU5SYJR8rmxVY8PiWfWQqK2CrMw6TDpHzxezfwS2b8v+5hLXpUZR5Waw9FhPLtRYx6OyhuTHIidPz89n0pRV09anLV9Oah+vskMsGbs89HiD61U+x1HCyLmu2gAmn2Lpj2W0I2J6C08B1P5ZyBtS8h51x74imMm2yZfEEBjL/gMKFDR7YaD5Pk04gg9NUCmOLLNW8hv3vQmzd3cJabj+9Jeb7X2wbEWur1X585nJEOMZ9ewHwT9GkuC+maFktpaVRmo0dEg7kYgQxL/VDKhueOh3dWAgkLuIh16fWgeN/nq5SGDGqtTLsnJlUOQOaZAzABD80+x1+GWPG12nfg9rvFqlIQWkNLS5dUhgkUW+71O+/J5LFhjt3LplLVo0/zIfAvSpqzglbkzsEz83ReVHMSXpUFX5Gimz96xkHoYLLUtGABjYcdyYwpLaw4Ea+521ifXwAss77mP3aGzYO3+QyDNHVNKLswPfpcJqRyvSVhYQfdthd6dngCN0E60StAQGGwKj/tk9BRPmtzs92DSnflQdp7DfR88s3Czz21FiWUVqbVV1Vpj8nNRG15qgGpAF6beX3tzg+OJv+r+uoZU6tGQfDW7Mo5l7Xz8YkFBQmNtnItGf5imWhonMerPeC8zlDdtuvkrin8ShvEk1dnnms=
jdk:
- openjdk8
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  provider: releases
  user: yanhuqing666
  file: target/*-linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
  draft: true
  password:
    secure: DcUi/I2yDDJqVeYqlf8G6F5ZhA6x4Br3GIAu1tIJ5oZnJptvb83TMzcYrmWUtbuF8+dkUsv8SY7ZpNTEHNDozSoFWzWXRR3Gyv5Jtr7Vc0OjrxJLqWK36RzGrebBvRfrisBKY1kTM102s7zHjmU1wxFx0rx5wyy70NJWLqlF8uBYKxDYy4h66rYJyxx5I2KLWoBGDddXympDw67O/mjCjJv6gUYmFc7s21Z+GGMDS89zlpzWGB8GZ5e8jv1HF6RNfyj1yMFGQa4l/L0ozgKJqNL06cJ4umjOCleWNZlzDgMaBc+4+QkdHQPKw3zQ7qb95cgykYyobnTUXXSZApsL107EGPXAI2OXcmVouQOGs9b0GEOuy1espBDqRFqUkm1JWwhtoFRdL4L9abDNA08Rj5nYn3RhWM6HwWhFNl0FC0shM+6H1yTgUmtQ6VyafAAVhVRBZxb5e1nXQK8gkqggXg+TKrNKi3MkxKzFuwokrIJMYNhi4fsLRJyHWPowvmlODWUyMdXufTzokgxCCGNbPQGSyu4OtEUVu5THs6MjNiNdMVwIO/m3KPcEzjGmrm5j3XQyphMI0K77UgyJT8ENjNLpjs6Nhx6UEieoQp0WDHIWbn6GKDJ1UHvssmuN5Q5JfRkIDJe0ZFx4B9NJ+4vp7eyowPHsaF02r/mHhTTbI4I=
