language: java
jdk:
  - openjdk8
  - oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: "yanhuqing666-github" # the key of the org you chose at step #3
    token:
      secure: ********* # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
