language: java
jdk:
- openjdk8
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  user: yanhuqing666
  file: target/*-linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
  draft: true
  password: AOIw6ISam+AGxohCoNJmhIbUdNSqDz60JLgqXVwTdZO2R+ZG3iM+E3vashQwuj+RcPdojrdpkUkXm4vGOpO0+5IyeiFaUtLgudMUBXmsAMdX8UsX3OQasEGcr2Rct77laMj/LJNi1QUZQ5rtNLKmflu5MFFlI4EW5Vdmu+IuPs0NmrevnEwBoVMlJSiABBtqMPhZ0fSn77kgHM2kYJOwFbRNXs8ngERg/UtbfC/XgaBp7wKR40JltnLgKzcxBZsMrTFXWl1u+Oxim7wYTYhhEIxuLRCGo1K8/O7FMz+vHMdH1KHTFhDPPfW8VYN3M4U3A0/wswj634ToKZGu5mO7cG5ZaKaFIXJS2Fvzv+kk8rQ9bV7qW2xKnmLYHRa0l67rmWZHx5RyP8jb0PYVgqtgL4Qku2Vo9kGNAjy61NUO4BcRhqLFW7Ky+4YXDiD1/f/y7O3ZJw/LxNiPx1uA8jbPrEd+LQf01nchyo9MexM+Gh7cCt1bKT0cnsPrQRmGPz06ww0My5/YktcWiKDc33FPYb2bZ4y/+zGfmttqM7NcG0om8ei8DxDqFpRTb8z5l6o26RjdKpPsX+l7O+iqA+CI3kj3lgT1x4ax3KPviXb6SW8My3+B42N+xxUc0rAlBvt+jcs2AuKSAelpHuikkNqD4l/x6D+JIRwCgha1oNU4KBU=
