language: java
jdk:
- openjdk8
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  user: yanhuqing666
  file: target/*-linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
  draft: true
  password:
    secure: UztTdJTf/wJ+q+c+gG3o895V06ZffoUG6iGKfsDbI+ZBwqsZ2Xb7QpEAOq6EbsFg1pTKDRQMnwmUM3f40OAhBHVnzhTuJXfrk2YwTXVnP4CIzFTWEZgCcjFklAvtCn/IuFrS67ipXvLMncxSq0TAebpetHBXe+BOttOKkrB4MRi5CYkMolO28d8/6qpk663cG6zpzeLdb5Bz6BY+U7eJv0w+Xt2daGvdwRzTRVa5RH9zWjnsJJ/PvWNl9OMRx+ZMqITAplJx/W6DNbTdlYrzDFoYFpCyNCFxJ1cAcibtvzf6oJiD5VAxtRbWi7hl5KWKtNxLEQVJTMNaZehtMof3CgHf3dGW7TjghVLTft00GWzhTAjEiicokEaZkEPCEta8qmBLAO4N3ja3RK4rnU5Df+Wt3AivOqYZCy0PI81uOcdwLZl9bV6JjYdALHaUJ/YW+9YnDhXDIsCCgQB4Cd+ndy7zUgSW1XJeWnjrTL0/8xpy6DKxrs316JFxLt5B9aWsd6LpG755uBs2QwNAwgcBsnMAj3cDVpS0AiFFca+G/3zIdbc2kA4j2egq3+X2Ky7oIGVfT4/i1sA7Kn/4fJkULWGsdYp3pq9J8hdrugPLPWh24ObA4OSuIccyo3gptc7m2d/moiKLeu6n5o8MjfNvmOqsC3b5dEsoEc3YRRtLbhk=
