language: java
jdk:
- openjdk8
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  api_key:
    secure: hoil3DyuxJNEoKvJAkfLfM7vuv1mKRQtOM6Lq2n70IarRZzhCOT6Htu1S/K2eJmrBP4OXFaZFVCgLxjbJOpO0/s27im1I3P1LOnLQJDRxouqvdGrsr5rET26LWmvPnhpBVMpg3dlIJxjkNjGwZkXNKo26fYUf0593MZIaMAfqh16cYiVmppHzsp6gDbchzkCmcHnypcXPtuf0cytrbhBsHuozX79yNhJYRJZgbkuxcdocjIJqDmytnTIStlAT+GLZn6Re3cRrwAVW0kWjxS80TjxnKfckrFc5lJyBozTS6NYPq6O9JNfNq08NRSYiKTwbPg6y5wwq81E1vEkdDkKuXpJCBsw/IBd0iN4s//az9P6C52ij8EnLpp93KZzFO8akPYDN2OcW5VMp2ttwEXKfx5lSaCxiA81H2m7j+AAjSf2vdWN5UI+MFhlkiZft8XuWvmhuSusbsUuGzsd97vCwpLSinCRBZpsB1zx/X50HrO4lqhwGyO4YstfhXV98QbXRh4dLvXJ+y3oXR79CvbyVQG0LMriJS2W5ezJWaRzFUaaHH25vPkWS/9eQvh580MlglTe8xOcAKrNPgoMzJKi7r6mz/8Xzus/iFTHC74+rznwdmOV5eCaVRoqDECFr8B7qjSCxURa7OQh/gibAdy0msAUTXRa3DIMobfORez2uC4=
  file: target/*-linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
  draft: true
