language: java
jdk:
- openjdk8
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  api_key:
    secure: NLL5ZmlxkuPJWAnctWawbCxl3/HP88U+LgvW5iNGi1603INb84g4ol32XeZaK9dBAo7vnweFBLhnLiv9jNm1yqiiFINKqXi4PIgscKYKbEI2X0rcYoStR2T+V6OEG0tEvNquuc+zMFi4mJLZN8MHeJ44zCq1XPeVEeL92ZctkBlR+057pFv158vH6M6WvTUUcGCmc+p+RuHMFcWEYVIbYaOyf8j0JOc2G6lGNmBG6zpmEsl/T/XwcI8EJlMLgZ/VETe3djbUWMK1ymSDEWa/iEsN/NXfnNrbXplOydO/7HkhvxNovKPaC0mushMzaDVmL2LjmFhDMloZCt4ZNctMofqLleDlDyzExDSvHVJ7+BrnC+e5h6MW+0fgu7j6Wr/ah/jlmtHfNOjMg9NIgMdq5nE/bASOWnYJGg5nOlTIr7GHW70NCItr4tH1jGJQkQa3Nbk9CLbYOn7o720fDiUtJugXcr92/cakTahq2OMJ3SVJsIbv/OqQaZHhvzFY7o9MtmQkBK5E5kBVNzsaBnx1jfEwOHTeo86yrScSPw/XVCBN1X1u7tEm6ryyqmgpek500M0/6dFBr8R9o8PM0ygDDjGm3P7n94zXrpvem5LoDX8O1wYt2xaovvh4W7g1BQuEtJhRenzeLPtSO9jibZHmphX/Op/tEUMnY4pPOL05+3c=
  file: target/*-linux.tar.gz
  on:
    tags: true
    jdk: openjdk8
  draft: true
  skip_cleanup: true
